#!/usr/bin/env php
<?php

$birthDate = "1989-10-02";
$todayDate = date("Y-m-d");

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs / (3600 * 24));

echo "$birthDate : $totalDays\n";
