#!/usr/bin/env php
<?php

include "src/Dates/BirthDays.php";

$birthDate = '1989-10-02';
$days = new \Glyanko\Dates\BirthDays($birthDate);

$totalDays = $days->findTotalDays();
echo "$birthDate: $totalDays\n";