#!/usr/bin/env php
<?php

require_once "vendor/autoload.php";

$birthDate = '1989-10-02';
$days = new \Glyanko\Dates\BirthDays($birthDate);

$totalDays = $days->findTotalDays();
echo "$birthDate: $totalDays\n";